# Generated by Django 5.0 on 2024-04-11 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprocedure',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handler_data.dataconfig'),
        ),
    ]
