# Generated by Django 5.0 on 2024-04-23 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('dashboard_layout', models.TextField(blank=True)),
                ('type_dashboard', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
