# Generated by Django 5.0 on 2024-06-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='database',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='driver',
            field=models.CharField(default='{ODBC Driver 17 for SQL Server}', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='server',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='uid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='uid_pass',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
