# Generated by Django 5.0 on 2024-06-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_company_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type_con',
            field=models.CharField(choices=[('Api', 'Api'), ('Server Sql', 'Server Sql')], default='Api', max_length=50, null=True),
        ),
    ]
