# Generated by Django 5.0 on 2024-04-16 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handler_data', '0004_dataconfig_config_sp_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('operation', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('variable_categorical', models.TextField(blank=True, null=True)),
                ('variable_numerical', models.TextField(blank=True, null=True)),
                ('figure', models.TextField(blank=True)),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('sp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handler_data.storeprocedure')),
            ],
        ),
    ]
